### ISSUE TITLE
SwooleResponseEmitter performace

### ISSUE THREAD

**Issue by n3vrax** [wshafer/swoole-expressive#1]
Not sure why, but I experience very low performance if using 
`$swooleResponse->write($content->getContents());`. 

I'm talking here a drop of request/sec to under 100. If I change it to `$swooleResponse->end(...)`, it works fast. Anyone experiencing this issue? 

Worth mentioning I enable -k (keep alive connection) on my ab test

**Comment by wshafer** [comment]
@n3vrax - Sorry for the delay.  I've been meaning to switch that from write to end but haven't gotten back to this yet.   I'm happy to accept a PR if you want to swap those out.

**Comment by wshafer** [comment]
Fixed in pr #2

Thanks again
